mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("search/outcome", views.outcome, name="outcome"),
    # ex: /polls/5/
    path("search/outcome/<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("search/outcome/<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("search/outcome/<int:question_id>/vote/", views.vote, name="vote"),
    path("search/outcome/<int:question_id>/add_rating/", views.add_rating, name='add_rating'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    description = models.CharField(max_length=10000, default="")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Rating(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    rating_str = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.rating_str

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.http import Http404
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic

from .models import Choice, Question, Rating

def index(request):
    return render(request, 'polls/index.html')

def search(request):
    if request.method == "POST":
        query = request.POST.get("question")
        try:
            question = Question.objects.get(question_text__icontains=query)
            return render(request, "polls/outcome.html", {"item": question, "question": question})
        except Question.DoesNotExist:
            return render(request, "polls/outcome.html", {"item": None})
'''
def search(request, question_id):
    latest_question_list = Question.objects.order_by("-pub_date")
    question = get_object_or_404(Question, pk=question_id)
    for item in latest_question_list:
        if item == question:
            context = {"item": item, "question": question}

            return render(request, "polls/outcome.html", context)
'''

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)  
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})

def add_rating(request, question_id):
    if request.method == "POST":
        question = get_object_or_404(Question, pk=question_id)
        

        rating_text = request.POST.get("rating_str")
        
        if rating_text:
            Rating.objects.create(question=question, rating_str=rating_text, votes=0)

        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))
    else:
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def outcome(request, question_id):
    latest_question_list = Question.objects.order_by("-pub_date")
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/outcome.html", context)

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Page</title>
    <style>
        body {
            background-color: #881c1c;
        }
    </style>
</head>
<body>
<p style="background-color: #e1e8ef; padding: 10px; border-radius: 5px;">{{ question.description }}</p>

<form action="{% url 'polls:add_rating' question.id %}" method="post">
    {% csrf_token %}
    <label for="new_rating">Enter a Rating:</label>
    <input type="text" name="rating_str" id="new_rating" required>
    <input type="submit" value="Submit Rating">
</form>
<br>
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        
        <!-- Display all choices for voting -->
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        
        <input type="submit" value="Vote">
    </fieldset>

    <br>

<!-- Display all ratings below the form -->
<h2>Reviews:</h2>
{% for rating in question.rating_set.all %}
    <p>{{ rating.rating_str }}</p>
{% empty %}
    <p>No reviews available for this question.</p>
{% endfor %}
</body>

mysite/polls/templates/polls/index.html

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/outcome.html
<!DOCTYPE html> <!--html is used to define structure/building blocks-->
{% load static %}
<html>  <!--indicates we are writing html code-->
    <head> <!--gives browser info about page-->
            <title>URateMyCourse</title><!--title of webpage -->
            <link rel="stylesheet" type="text/css" href="{% static 'polls/css/stylesheet.css' %}">
            <script src="{% static 'polls/js/script.js' %}" defer></script>
    </head> 
    <body>
        <div class="centercontainer" float="left">
            <img src="{% static 'polls/images/logo.png' %}" length="200" width="200">
        </div>

        <button class="tablink" onclick="openPage('Home', this, '#ffffff')" id="defaultOpen">Home</button>
        <button class="tablink" onclick="openPage('About', this, '#ffffff')">About</button>        
        </div>

        <div id="Home" class="tabcontent">
            <h3 style="text-align: center;">Search Result</h3>
            <div class="centercontainer">
                {% if item %}
                <ul>
                    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
                {% else %}
                    <p>No polls are available.</p>
                {% endif %}
            </div>
            <div class="centercontainer" width="100%" height="100vh" object-fit="cover">
                <img src="{% static 'polls/images/UMassPic.png' %}" alt="UMass Campus">
            </div>

        </div>
          
        <div id="About" class="tabcontent">
            <h3>Search Classes</h3>
            <p>Some news this fine day!</p> 
        </div>


    </body>





</html>

mysite/polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/stylesheet.css' %}">
<script src="{% static 'polls/js/script.js' %}" defer></script>
<div class="centercontainer" width="100%" height="100vh" object-fit="cover">
    <img src="{% static 'polls/images/UMassPic.png' %}" alt="UMass Campus">
</div>
<body style="background-color: #881c1c; padding: 10px; border-radius: 5px;">
<h1 style="color: white;">{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li style="color: white;">{{ choice.choice_text }} star -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}" style="color: white;">Go back to the class?</a>
</body>